{
  "kind": "strategy#objective",
  "typeOf": "Strategy Objective",
  "etag": "",
  "uid": "",
  "id": "212121",
  "parentId": "",
  "keywords": "",
  "categories": "",
  "name": " ",
  "description": "",
  "owner": "",
  "measures": [],
  "objectives": [],
  "initiatives": [],
  "from-to-gap": "",
  "perspective": "",
  "theme": "",
  "document": "",
  "image": "",
  "shortname": ""
}